In [11]:
import pandas as pd
import numpy as np

In [4]:
np_height=np.array([176, 178, 182, 184, 185])

In [5]:
np_weight=np.array([72, 75, 76, 78, 85])

In [6]:
bmi=np_height/np_weight

In [7]:
print(bmi)

[2.44444444 2.37333333 2.39473684 2.35897436 2.17647059]


In [8]:
bmi>2.3

array([ True,  True,  True,  True, False])

In [9]:
bmi[bmi>2.3]

array([2.44444444, 2.37333333, 2.39473684, 2.35897436])

In [10]:
2<3

True

In [11]:
2==3

False

In [12]:
2<=3

True

In [13]:
3<=3

True

In [15]:
z=4
if z%2==0:
    print("z is even")

z is even


In [22]:
z=5
if z%2==0:
    print("z is even")
else :
        print("z is odd")

z is odd


In [24]:
z=3
if z%2==0:
    print("z is ok")
elif z%3==0:
    print("zzzzzz")
else:
    print("clear")

zzzzzz


In [26]:
print(true == false)

NameError: name 'true' is not defined

In [27]:
print(5*15!=75)

False


In [28]:
print("pyScript"=="pyscript")

False


In [29]:
print(true==1)

NameError: name 'true' is not defined

In [31]:
x=-3*6
print(x<-10)

True


In [33]:
y="test"
print("test"<=y)

True


In [34]:
print(true>false)

NameError: name 'true' is not defined

In [35]:
my_house=np.array([23,34,45,56])

In [36]:
ur_house=np.array([21,22,23,24])

In [37]:
print(my_house>30)

[False  True  True  True]


In [39]:
print(my_house==ur_house)

[False False False False]


In [40]:
my_kitchen=18.0

In [41]:
ur_kitchen=14.0

In [42]:
print(my_kitchen==18 and ur_kitchen<15)

True


In [43]:
print(my_kitchen>20 or ur_kitchen<15)

True


In [44]:
print(my_kitchen*3==ur_kitchen*4)

False


In [47]:
print(np.logical_or(my_house>14,ur_house==21))

[ True  True  True  True]


In [48]:
print(np.logical_and(my_house>14,ur_house==21))

[ True False False False]


In [2]:
room="kit"
area=14.0

In [3]:
if room=="kit":
    print("check done")


check done


In [7]:
if room=="kity":
    print("no name")
elif area>15:
    print("name found")
else:
    print("its working")

its working


In [10]:
!pip install pandas
!pip install numpy

In [12]:
prac=pd.read_excel('C:\\Users\\user\\Desktop\\Anil_sheet.xlsx')

In [13]:
prac.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='object')

In [15]:
prac1=prac[['InvoiceNo', 'StockCode', 'Description']]

In [17]:
prac1.columns

Index(['InvoiceNo', 'StockCode', 'Description'], dtype='object')

In [44]:
invoice=prac1['StockCode']


In [37]:
invoice_1=np.array(invoice)

In [46]:
invo=invoice=22752




In [48]:
check=invoice[invo]

TypeError: 'int' object is not subscriptable